/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
// GL2.0 API
#include "XLog.h"
/* Header for class com_xiaxl_test_Hello */

#ifndef _Included_com_xiaxl_demo_Hello
#define _Included_com_xiaxl_demo_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaxl_test_Hello
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xiaxl_demo_Hello_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
